/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "stdio.h"
#include "stdint.h"

void init_fault_handler(void);
extern initialise_monitor_handles();
int main(void)
{
    /* Loop forever */
	initialise_monitor_handles();

	init_fault_handler();

	int x=10,y=0,z=0;

	z=x/y;

	for(;;);
}

void init_fault_handler(void)
{
	//System Handler Control and State Register
	uint32_t *pSHCRS = (uint32_t *)0xE000ED24;

	uint32_t * pCCR = (uint32_t*)0xE000ED14;

	//enable MEMFAULT
	*pSHCRS = ( 1 << 16 );

	//enable BUSFAULT
	*pSHCRS = ( 1 << 17 );

	//enable USAGEFAULT
	*pSHCRS = ( 1 << 18 );

	//enable divide by zero fault
	//*pCCR |= ( 1 << 4 );
}

/* This function(ISR) executes in HANDLER MODE of the processor */
void EXTI22_RTC_WKUP_IRQHandler(void)
{
	//printf("In handler mode : ISR\n");
	__asm volatile ("nop");
}

void MemManage_Handler(void)
{
	while(1);
}

void BusFault_Handler(void)
{
	while(1);
}
__attribute__ ((naked)) void UsageFault_Handler(void)
{
	__asm ("MRS r0,MSP");
	__asm ("B UsageFault_Handler_c");
}
void UsageFault_Handler_c(uint32_t * pBaseStackFrame)
{
//	__asm ("MRS r0,MSP");
//	register uint32_t msp_value __asm ("r0");
//	uint32_t *pMSP = (uint32_t *)msp_value;

	/* not able to print but could check the value at addresses by adding
	 *pBaseStackFrame +4 = R0
	 *pBaseStackFrame +8 = R1
	 *pBaseStackFrame +12 = R2
	 *pBaseStackFrame  + 16 = R3
	 *pBaseStackFrame  + 20 = R12
	 *pBaseStackFrame  + 24 = LR
	 *pBaseStackFrame  + 28 = PC
	 *pBaseStackFrame  + 32 = XPSR*/
	printf("MSP = %p\n",pBaseStackFrame);
	printf("Value of R0 = %lx\n", pBaseStackFrame[0]);
	printf("Value of R1 = %lx\n", pBaseStackFrame[1]);
	printf("Value of R2 = %lx\n", pBaseStackFrame[2]);
	printf("Value of R3 = %lx\n", pBaseStackFrame[3]);
	printf("Value of R12 = %lx\n", pBaseStackFrame[4]);
	printf("Value of LR = %lx\n", pBaseStackFrame[5]);
	printf("Value of PC = %lx\n", pBaseStackFrame[6]);
	printf("Value of XPSR = %lx\n", pBaseStackFrame[7]);
	while(1);
}

void HardFault_Handler(void)
{
	while(1);
}
